matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'valgrind']
    - os: osx
      compiler: clang
dist: trusty
sudo: required
language:
  - cpp
#before_script:
#  - sudo pip install pexpect
script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      export CC=gcc-6;
      export CXX=g++-6;
      make shuffle;
      fi;
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      export TAR_FLAG=-target x86_64-darwin;
      make shuffle;
      fi; 
after_success:
  - if [ "$CXX" == "g++-6" ]; then
        cd test_results;
        bash <(curl -s https://codecov.io/bash);
    fi;
